# Generated by Django 5.0.4 on 2024-06-30 11:57

import events.utils.image_path
import events.utils.pk_genrator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(default=events.utils.pk_genrator.generate_id, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(null=True, upload_to=events.utils.image_path.image_file_path)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
