# Generated by Django 5.0.4 on 2024-07-03 09:33

import events.utils.fields.pk_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_category_event_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', events.utils.fields.pk_field.PrimaryKeyField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='show_owner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='telegram_channel',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.tag'),
        ),
    ]
