version: 1.0.0

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./BackEnd:/app
    ports:
      - "8000:8000"
    command: >
        sh -c "python manage.py runserver 0.0.0.0:8000"
