name: Checks

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check Out
        uses: actions/checkout@v3

      - name: Print Directory Structure
        run: ls -R

      - name: Build Docker Images
        run: docker-compose build
        working-directory: .

      - name: Wait for DataBase to be available
        run: docker-compose run --rm backend python manage.py wait_for_db
        working-directory: .

      - name: Run BackEnd Test
        run: docker-compose run --rm backend python manage.py test
        working-directory: .
